
language: node_js

node_js:
  - '6'

addons:
  apt:
    packages:
      - xvfb

before_script:
  - chmod -R +x sh
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - export DISPLAY=':99.0'
  - export RELEASE_MODE=TRUE
